#define T_Eof                             1
#define T_LBrace                          2
#define T_RBrace                          3
#define T_Import                          4
#define T_Identifier                      5
#define T_Semicolon                       6
#define T_From                            7
#define T_Dot                             8
#define T_As                              9
#define T_Return                         10
#define T_Assign                         11
#define T_Mixed                          12
#define T_Function                       13
#define T_Colon                          14
#define T_LParenthesis                   15
#define T_RParenthesis                   16
#define T_Void                           17
#define T_Comma                          18
#define T_Class                          19
#define T_Public                         20
#define T_Private                        21
#define T_AssignNumericAddition          22
#define T_AssignNumericSubstraction      23
#define T_AssignNumericMultiplication    24
#define T_AssignNumericDivision          25
#define T_AssignNumericModulo            26
#define T_AssignBinaryAnd                27
#define T_AssignBinaryOr                 28
#define T_AssignBinaryXor                29
#define T_AssignBinaryLShift             30
#define T_AssignBinaryRShift             31
#define T_LogicalOr                      32
#define T_LogicalAnd                     33
#define T_BinaryOr                       34
#define T_BinaryXor                      35
#define T_BinaryAnd                      36
#define T_RelationalEqual                37
#define T_RelationalDifferent            38
#define T_RelationalLesser               39
#define T_RelationalGreater              40
#define T_RelationalLesserOrEqual        41
#define T_RelationalGreaterOrEqual       42
#define T_BinaryLShift                   43
#define T_BinaryRShift                   44
#define T_NumericAddition                45
#define T_NumericSubstraction            46
#define T_NumericMultiplication          47
#define T_NumericDivision                48
#define T_NumericModulo                  49
#define T_Increment                      50
#define T_Decrement                      51
#define T_BinaryNot                      52
#define T_LogicalNot                     53
#define T_LBracket                       54
#define T_RBracket                       55
#define T_New                            56
#define T_This                           57
#define T_Super                          58
#define T_Number                         59
#define T_String                         60
