#define Eof                             1
#define LBrace                          2
#define RBrace                          3
#define Import                          4
#define Identifier                      5
#define Semicolon                       6
#define From                            7
#define Dot                             8
#define As                              9
#define Return                         10
#define Assign                         11
#define Mixed                          12
#define Function                       13
#define Colon                          14
#define LParenthesis                   15
#define RParenthesis                   16
#define Void                           17
#define Comma                          18
#define Class                          19
#define Public                         20
#define Private                        21
#define AssignNumericAddition          22
#define AssignNumericSubstraction      23
#define AssignNumericMultiplication    24
#define AssignNumericDivision          25
#define AssignNumericModulo            26
#define AssignBinaryAnd                27
#define AssignBinaryOr                 28
#define AssignBinaryXor                29
#define AssignBinaryLShift             30
#define AssignBinaryRShift             31
#define LogicalOr                      32
#define LogicalAnd                     33
#define BinaryOr                       34
#define BinaryXor                      35
#define BinaryAnd                      36
#define RelationalEqual                37
#define RelationalDifferent            38
#define RelationalLesser               39
#define RelationalGreater              40
#define RelationalLesserOrEqual        41
#define RelationalGreaterOrEqual       42
#define BinaryLShift                   43
#define BinaryRShift                   44
#define NumericAddition                45
#define NumericSubstraction            46
#define NumericMultiplication          47
#define NumericDivision                48
#define NumericModulo                  49
#define Increment                      50
#define Decrement                      51
#define BinaryNot                      52
#define LogicalNot                     53
#define LBracket                       54
#define RBracket                       55
#define New                            56
#define This                           57
#define Super                          58
#define Number                         59
#define String                         60
