#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Assignment                      1
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_AdditionAssignment              2
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_SubstractionAssignment          3
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_MultiplicationAssignment        4
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_DivisionAssignment              5
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_ModuloAssignment                6
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_PositiveAddition                7
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_NegativeSubstraction            8
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Multiplication                  9
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Division                       10
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Modulo                         11
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_LParenthesis                   12
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_LBracket                       13
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Spaces                         14
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Newline                        15
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Indent                         16
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Dedent                         17
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Return                         18
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Var                            19
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Comma                          20
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Identifier                     21
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Assign                         22
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_If                             23
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Colon                          24
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Else                           25
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Incrementation                 26
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Decrementation                 27
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_RParenthesis                   28
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_RBracket                       29
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_False                          30
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_True                           31
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Function                       32
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Null                           33
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Number                         34
#define CASTEL_LEXER_MANGLEDLEXEMESTYPES_Undefined                      35
