find_program(LLVM_CONFIG_EXECUTABLE NAMES "${LLVM_PATH}/bin/llvm-config" DOC "llvm-config executable")

execute_process(
    COMMAND "${LLVM_CONFIG_EXECUTABLE}" --cppflags
    OUTPUT_VARIABLE LLVM_CXX_FLAGS
    OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(
    COMMAND "${LLVM_CONFIG_EXECUTABLE}" --ldflags
    OUTPUT_VARIABLE LLVM_LINK_FLAGS
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
    COMMAND "${LLVM_CONFIG_EXECUTABLE}" --libs all
    OUTPUT_VARIABLE LLVM_LIBRARIES_ALL
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
